### ISSUE TITLE
Unordered List of photos is not aesthetically pleasing

### ISSUE THREAD

**Issue by thuibr** [dannystey/grav-plugin-instagram-feed#1]
I may not know how to use this plugin correctly. How would I go about displaing the photos horizontally like towards the bottom of http://www.rainforest-alliance.org/

**Comment by dannystey** [comment]
as default the images will be displayed as an unorderd list ( ul > li ) you could create your own template and provide it through the functions like that `{{ instagram_feed('path/to/template.html.twig') }}` so that you can create your own markup... the plugin does not come with any stylings. 

but if you add this following to your stylesheet, it may display the feed in a line.

```
.instagram-feed {
 list-style: none;
 margin: 0;
 padding: 0;
 display: flex;
}

.instagram-feed li {
 flex: 1;
 margin: 0 0.5em;
}
```

If it does not help could you provide an url?

**Comment by thuibr** [comment]
I am trying to set up a modular page .html.twig so that I can embed instagram into modular pages. Assuming I have
`{{ instagram_feed() }}`
what's the bare minimum I need to do to setup this .html.twig to show instagram images in a horizontal line? I apologize because I am a novice at this. I work in embedded and am volunteering to update a website for a club that I am involved in.

**Comment by thuibr** [comment]
I forgot to mention, right now the site is in development on my local machine, so I do not have a URL for you.

**Comment by dannystey** [comment]
to show a instagram feed in horizontal way you have to use css ... the page that you mentioned uses unordered list for the feed as well. its only a thing of your styling. did you tried the css above ? does it work?

**Comment by thuibr** [comment]
I finally got it to work. Thank you! My code looks like so:
```
{% block stylesheets %}
    {% do assets.addCss('theme://css/instagram.css') %}
{% endblock %}
{{ assets.css() }}

{{ instagram_feed() }}
```
Is this good twig file style? The stylesheet above is in its own .css file.
